services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./view:/usr/share/nginx/html